# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

############################################################
# General Configuration
############################################################
site_name: Visual Update Documentation
site_author: Soner Boztas & Contributors
copyright: Copyright &copy; 2010-[Year] solicus. Last build on [Date]. Revision&colon; [CommitHash]. Branch&colon; [Branch].

site_url: https://docs.visualupdate.net
repo_url: https://github.com/soner-boztas/visual-update-express-docs
edit_uri: edit/main/docs/

site_dir: !ENV [ DOCS_BUILD_FOLDER_NAME ]

############################################################
# Navigation
############################################################
nav:
  - Home: index.md
  - Getting Started:
      - getting-started/index.md
      - Introduction: getting-started/introduction.md
      - Features: getting-started/features.md
      - Terminology: getting-started/terminology.md
      - System Prerequisites: getting-started/system-prerequisites.md
      - Installation: getting-started/installation.md
      - Quick Start Guide: getting-started/quick-start-guide.md
  - Reference:
    - reference/index.md
    - Update Script: reference/update-script.md
    - Path Constants: reference/path-constants.md
  - FAQ:
      - faq/index.md
  - Release Notes:
      - release-notes/index.md
  - Contributing:
      - contributing/index.md
      - Asking a Question: contributing/asking-a-question.md
      - Reporting a Bug: contributing/reporting-a-bug.md
      - Requesting a New Feature: contributing/requesting-a-new-feature.md
      - Making a Donation: contributing/making-a-donation.md
  - License:
      - license/index.md
      - Visual Update Community: license/community-eula.md
      - Visual Update Pro: license/pro-eula.md

############################################################
# Theme Configuration
############################################################
theme:
  name: material
  language: en

  font:
    text: Open Sans
    code: Roboto Mono

  logo: assets/vue-logo.png
  favicon: assets/vue-favicon.ico

  icon:
    edit: material/pencil
    view: material/eye

  palette:
    # Palette toggle for light mode.
    - scheme: visualupdate-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode.
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - search
    - search.suggest
    - search.highlight
    - search.share

############################################################
# Plugins
############################################################
plugins:
  - search
  - table-reader
  - privacy:
      enabled: !ENV [ IS_BUILD, false ]
  - git-revision-date-localized:
      enabled: !ENV [ IS_BUILD, false ]
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [ IS_BUILD, false ]
      repository: soner-boztas/visual-update-docs
      branch: main

############################################################
# Markdown Extensions
############################################################
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - glossary.md
        - common_links.md

############################################################
# Extras
############################################################
extra:
  # Disable the "Made with Material for MkDocs" notice.
  generator: false

  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/solicusoftware
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/solicus
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/86189712/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCUN8s7e_rPTEs7FVG3naw2w

extra_css:
  - stylesheets/extra.css
